# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hacker/github/snowball.repo/gear-lib

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hacker/github/snowball.repo/gear-lib

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hacker/github/snowball.repo/gear-lib/CMakeFiles /home/hacker/github/snowball.repo/gear-lib/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hacker/github/snowball.repo/gear-lib/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dict

# Build rule for target.
dict: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dict
.PHONY : dict

# fast build rule for target.
dict/fast:
	$(MAKE) -f CMakeFiles/dict.dir/build.make CMakeFiles/dict.dir/build
.PHONY : dict/fast

#=============================================================================
# Target rules for targets named ipc

# Build rule for target.
ipc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ipc
.PHONY : ipc

# fast build rule for target.
ipc/fast:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/build
.PHONY : ipc/fast

#=============================================================================
# Target rules for targets named file

# Build rule for target.
file: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 file
.PHONY : file

# fast build rule for target.
file/fast:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/build
.PHONY : file/fast

#=============================================================================
# Target rules for targets named gevent

# Build rule for target.
gevent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gevent
.PHONY : gevent

# fast build rule for target.
gevent/fast:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/build
.PHONY : gevent/fast

#=============================================================================
# Target rules for targets named log

# Build rule for target.
log: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 log
.PHONY : log

# fast build rule for target.
log/fast:
	$(MAKE) -f CMakeFiles/log.dir/build.make CMakeFiles/log.dir/build
.PHONY : log/fast

#=============================================================================
# Target rules for targets named vector

# Build rule for target.
vector: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 vector
.PHONY : vector

# fast build rule for target.
vector/fast:
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/build
.PHONY : vector/fast

#=============================================================================
# Target rules for targets named queue

# Build rule for target.
queue: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 queue
.PHONY : queue

# fast build rule for target.
queue/fast:
	$(MAKE) -f CMakeFiles/queue.dir/build.make CMakeFiles/queue.dir/build
.PHONY : queue/fast

src/epoll.o: src/epoll.c.o

.PHONY : src/epoll.o

# target to build an object file
src/epoll.c.o:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/epoll.c.o
.PHONY : src/epoll.c.o

src/epoll.i: src/epoll.c.i

.PHONY : src/epoll.i

# target to preprocess a source file
src/epoll.c.i:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/epoll.c.i
.PHONY : src/epoll.c.i

src/epoll.s: src/epoll.c.s

.PHONY : src/epoll.s

# target to generate assembly for a file
src/epoll.c.s:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/epoll.c.s
.PHONY : src/epoll.c.s

src/filewatcher.o: src/filewatcher.c.o

.PHONY : src/filewatcher.o

# target to build an object file
src/filewatcher.c.o:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/filewatcher.c.o
.PHONY : src/filewatcher.c.o

src/filewatcher.i: src/filewatcher.c.i

.PHONY : src/filewatcher.i

# target to preprocess a source file
src/filewatcher.c.i:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/filewatcher.c.i
.PHONY : src/filewatcher.c.i

src/filewatcher.s: src/filewatcher.c.s

.PHONY : src/filewatcher.s

# target to generate assembly for a file
src/filewatcher.c.s:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/filewatcher.c.s
.PHONY : src/filewatcher.c.s

src/fio.o: src/fio.c.o

.PHONY : src/fio.o

# target to build an object file
src/fio.c.o:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/fio.c.o
.PHONY : src/fio.c.o

src/fio.i: src/fio.c.i

.PHONY : src/fio.i

# target to preprocess a source file
src/fio.c.i:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/fio.c.i
.PHONY : src/fio.c.i

src/fio.s: src/fio.c.s

.PHONY : src/fio.s

# target to generate assembly for a file
src/fio.c.s:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/fio.c.s
.PHONY : src/fio.c.s

src/io.o: src/io.c.o

.PHONY : src/io.o

# target to build an object file
src/io.c.o:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/io.c.o
.PHONY : src/io.c.o

src/io.i: src/io.c.i

.PHONY : src/io.i

# target to preprocess a source file
src/io.c.i:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/io.c.i
.PHONY : src/io.c.i

src/io.s: src/io.c.s

.PHONY : src/io.s

# target to generate assembly for a file
src/io.c.s:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/io.c.s
.PHONY : src/io.c.s

src/libdict.o: src/libdict.c.o

.PHONY : src/libdict.o

# target to build an object file
src/libdict.c.o:
	$(MAKE) -f CMakeFiles/dict.dir/build.make CMakeFiles/dict.dir/src/libdict.c.o
.PHONY : src/libdict.c.o

src/libdict.i: src/libdict.c.i

.PHONY : src/libdict.i

# target to preprocess a source file
src/libdict.c.i:
	$(MAKE) -f CMakeFiles/dict.dir/build.make CMakeFiles/dict.dir/src/libdict.c.i
.PHONY : src/libdict.c.i

src/libdict.s: src/libdict.c.s

.PHONY : src/libdict.s

# target to generate assembly for a file
src/libdict.c.s:
	$(MAKE) -f CMakeFiles/dict.dir/build.make CMakeFiles/dict.dir/src/libdict.c.s
.PHONY : src/libdict.c.s

src/libfile.o: src/libfile.c.o

.PHONY : src/libfile.o

# target to build an object file
src/libfile.c.o:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/libfile.c.o
.PHONY : src/libfile.c.o

src/libfile.i: src/libfile.c.i

.PHONY : src/libfile.i

# target to preprocess a source file
src/libfile.c.i:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/libfile.c.i
.PHONY : src/libfile.c.i

src/libfile.s: src/libfile.c.s

.PHONY : src/libfile.s

# target to generate assembly for a file
src/libfile.c.s:
	$(MAKE) -f CMakeFiles/file.dir/build.make CMakeFiles/file.dir/src/libfile.c.s
.PHONY : src/libfile.c.s

src/libgevent.o: src/libgevent.c.o

.PHONY : src/libgevent.o

# target to build an object file
src/libgevent.c.o:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/libgevent.c.o
.PHONY : src/libgevent.c.o

src/libgevent.i: src/libgevent.c.i

.PHONY : src/libgevent.i

# target to preprocess a source file
src/libgevent.c.i:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/libgevent.c.i
.PHONY : src/libgevent.c.i

src/libgevent.s: src/libgevent.c.s

.PHONY : src/libgevent.s

# target to generate assembly for a file
src/libgevent.c.s:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/libgevent.c.s
.PHONY : src/libgevent.c.s

src/libipc.o: src/libipc.c.o

.PHONY : src/libipc.o

# target to build an object file
src/libipc.c.o:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/libipc.c.o
.PHONY : src/libipc.c.o

src/libipc.i: src/libipc.c.i

.PHONY : src/libipc.i

# target to preprocess a source file
src/libipc.c.i:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/libipc.c.i
.PHONY : src/libipc.c.i

src/libipc.s: src/libipc.c.s

.PHONY : src/libipc.s

# target to generate assembly for a file
src/libipc.c.s:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/libipc.c.s
.PHONY : src/libipc.c.s

src/liblog.o: src/liblog.c.o

.PHONY : src/liblog.o

# target to build an object file
src/liblog.c.o:
	$(MAKE) -f CMakeFiles/log.dir/build.make CMakeFiles/log.dir/src/liblog.c.o
.PHONY : src/liblog.c.o

src/liblog.i: src/liblog.c.i

.PHONY : src/liblog.i

# target to preprocess a source file
src/liblog.c.i:
	$(MAKE) -f CMakeFiles/log.dir/build.make CMakeFiles/log.dir/src/liblog.c.i
.PHONY : src/liblog.c.i

src/liblog.s: src/liblog.c.s

.PHONY : src/liblog.s

# target to generate assembly for a file
src/liblog.c.s:
	$(MAKE) -f CMakeFiles/log.dir/build.make CMakeFiles/log.dir/src/liblog.c.s
.PHONY : src/liblog.c.s

src/libqueue.o: src/libqueue.c.o

.PHONY : src/libqueue.o

# target to build an object file
src/libqueue.c.o:
	$(MAKE) -f CMakeFiles/queue.dir/build.make CMakeFiles/queue.dir/src/libqueue.c.o
.PHONY : src/libqueue.c.o

src/libqueue.i: src/libqueue.c.i

.PHONY : src/libqueue.i

# target to preprocess a source file
src/libqueue.c.i:
	$(MAKE) -f CMakeFiles/queue.dir/build.make CMakeFiles/queue.dir/src/libqueue.c.i
.PHONY : src/libqueue.c.i

src/libqueue.s: src/libqueue.c.s

.PHONY : src/libqueue.s

# target to generate assembly for a file
src/libqueue.c.s:
	$(MAKE) -f CMakeFiles/queue.dir/build.make CMakeFiles/queue.dir/src/libqueue.c.s
.PHONY : src/libqueue.c.s

src/libvector.o: src/libvector.c.o

.PHONY : src/libvector.o

# target to build an object file
src/libvector.c.o:
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/src/libvector.c.o
.PHONY : src/libvector.c.o

src/libvector.i: src/libvector.c.i

.PHONY : src/libvector.i

# target to preprocess a source file
src/libvector.c.i:
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/src/libvector.c.i
.PHONY : src/libvector.c.i

src/libvector.s: src/libvector.c.s

.PHONY : src/libvector.s

# target to generate assembly for a file
src/libvector.c.s:
	$(MAKE) -f CMakeFiles/vector.dir/build.make CMakeFiles/vector.dir/src/libvector.c.s
.PHONY : src/libvector.c.s

src/msgq_posix.o: src/msgq_posix.c.o

.PHONY : src/msgq_posix.o

# target to build an object file
src/msgq_posix.c.o:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/msgq_posix.c.o
.PHONY : src/msgq_posix.c.o

src/msgq_posix.i: src/msgq_posix.c.i

.PHONY : src/msgq_posix.i

# target to preprocess a source file
src/msgq_posix.c.i:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/msgq_posix.c.i
.PHONY : src/msgq_posix.c.i

src/msgq_posix.s: src/msgq_posix.c.s

.PHONY : src/msgq_posix.s

# target to generate assembly for a file
src/msgq_posix.c.s:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/msgq_posix.c.s
.PHONY : src/msgq_posix.c.s

src/msgq_sysv.o: src/msgq_sysv.c.o

.PHONY : src/msgq_sysv.o

# target to build an object file
src/msgq_sysv.c.o:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/msgq_sysv.c.o
.PHONY : src/msgq_sysv.c.o

src/msgq_sysv.i: src/msgq_sysv.c.i

.PHONY : src/msgq_sysv.i

# target to preprocess a source file
src/msgq_sysv.c.i:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/msgq_sysv.c.i
.PHONY : src/msgq_sysv.c.i

src/msgq_sysv.s: src/msgq_sysv.c.s

.PHONY : src/msgq_sysv.s

# target to generate assembly for a file
src/msgq_sysv.c.s:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/msgq_sysv.c.s
.PHONY : src/msgq_sysv.c.s

src/netlink.o: src/netlink.c.o

.PHONY : src/netlink.o

# target to build an object file
src/netlink.c.o:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/netlink.c.o
.PHONY : src/netlink.c.o

src/netlink.i: src/netlink.c.i

.PHONY : src/netlink.i

# target to preprocess a source file
src/netlink.c.i:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/netlink.c.i
.PHONY : src/netlink.c.i

src/netlink.s: src/netlink.c.s

.PHONY : src/netlink.s

# target to generate assembly for a file
src/netlink.c.s:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/netlink.c.s
.PHONY : src/netlink.c.s

src/poll.o: src/poll.c.o

.PHONY : src/poll.o

# target to build an object file
src/poll.c.o:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/poll.c.o
.PHONY : src/poll.c.o

src/poll.i: src/poll.c.i

.PHONY : src/poll.i

# target to preprocess a source file
src/poll.c.i:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/poll.c.i
.PHONY : src/poll.c.i

src/poll.s: src/poll.c.s

.PHONY : src/poll.s

# target to generate assembly for a file
src/poll.c.s:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/poll.c.s
.PHONY : src/poll.c.s

src/select.o: src/select.c.o

.PHONY : src/select.o

# target to build an object file
src/select.c.o:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/select.c.o
.PHONY : src/select.c.o

src/select.i: src/select.c.i

.PHONY : src/select.i

# target to preprocess a source file
src/select.c.i:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/select.c.i
.PHONY : src/select.c.i

src/select.s: src/select.c.s

.PHONY : src/select.s

# target to generate assembly for a file
src/select.c.s:
	$(MAKE) -f CMakeFiles/gevent.dir/build.make CMakeFiles/gevent.dir/src/select.c.s
.PHONY : src/select.c.s

src/shm.o: src/shm.c.o

.PHONY : src/shm.o

# target to build an object file
src/shm.c.o:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/shm.c.o
.PHONY : src/shm.c.o

src/shm.i: src/shm.c.i

.PHONY : src/shm.i

# target to preprocess a source file
src/shm.c.i:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/shm.c.i
.PHONY : src/shm.c.i

src/shm.s: src/shm.c.s

.PHONY : src/shm.s

# target to generate assembly for a file
src/shm.c.s:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/shm.c.s
.PHONY : src/shm.c.s

src/unix_socket.o: src/unix_socket.c.o

.PHONY : src/unix_socket.o

# target to build an object file
src/unix_socket.c.o:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/unix_socket.c.o
.PHONY : src/unix_socket.c.o

src/unix_socket.i: src/unix_socket.c.i

.PHONY : src/unix_socket.i

# target to preprocess a source file
src/unix_socket.c.i:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/unix_socket.c.i
.PHONY : src/unix_socket.c.i

src/unix_socket.s: src/unix_socket.c.s

.PHONY : src/unix_socket.s

# target to generate assembly for a file
src/unix_socket.c.s:
	$(MAKE) -f CMakeFiles/ipc.dir/build.make CMakeFiles/ipc.dir/src/unix_socket.c.s
.PHONY : src/unix_socket.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... dict"
	@echo "... ipc"
	@echo "... file"
	@echo "... gevent"
	@echo "... log"
	@echo "... vector"
	@echo "... queue"
	@echo "... src/epoll.o"
	@echo "... src/epoll.i"
	@echo "... src/epoll.s"
	@echo "... src/filewatcher.o"
	@echo "... src/filewatcher.i"
	@echo "... src/filewatcher.s"
	@echo "... src/fio.o"
	@echo "... src/fio.i"
	@echo "... src/fio.s"
	@echo "... src/io.o"
	@echo "... src/io.i"
	@echo "... src/io.s"
	@echo "... src/libdict.o"
	@echo "... src/libdict.i"
	@echo "... src/libdict.s"
	@echo "... src/libfile.o"
	@echo "... src/libfile.i"
	@echo "... src/libfile.s"
	@echo "... src/libgevent.o"
	@echo "... src/libgevent.i"
	@echo "... src/libgevent.s"
	@echo "... src/libipc.o"
	@echo "... src/libipc.i"
	@echo "... src/libipc.s"
	@echo "... src/liblog.o"
	@echo "... src/liblog.i"
	@echo "... src/liblog.s"
	@echo "... src/libqueue.o"
	@echo "... src/libqueue.i"
	@echo "... src/libqueue.s"
	@echo "... src/libvector.o"
	@echo "... src/libvector.i"
	@echo "... src/libvector.s"
	@echo "... src/msgq_posix.o"
	@echo "... src/msgq_posix.i"
	@echo "... src/msgq_posix.s"
	@echo "... src/msgq_sysv.o"
	@echo "... src/msgq_sysv.i"
	@echo "... src/msgq_sysv.s"
	@echo "... src/netlink.o"
	@echo "... src/netlink.i"
	@echo "... src/netlink.s"
	@echo "... src/poll.o"
	@echo "... src/poll.i"
	@echo "... src/poll.s"
	@echo "... src/select.o"
	@echo "... src/select.i"
	@echo "... src/select.s"
	@echo "... src/shm.o"
	@echo "... src/shm.i"
	@echo "... src/shm.s"
	@echo "... src/unix_socket.o"
	@echo "... src/unix_socket.i"
	@echo "... src/unix_socket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

