/* Automatically generated by version.sh - do not modify! */
#ifndef LIBHOMEKIT_VERSION_H
#define LIBHOMEKIT_VERSION_H

#define libhomekit_version 0.1.0
#define libhomekit_buildid git-2019-09-21-1acd320

#endif

