# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('libc', src, 
    depend = ['RT_USING_GEARLIB'],
    CPPPATH = CPPPATH)

Return('group')

